### ISSUE TITLE
Assignment 1 - API server checklist

### ISSUE THREAD

**Issue by lctoye** [lctoye/fragments#1]
## API Server Checklist

- [x] fragments git repo set up correctly (e.g., README, .gitignore, etc)
- [x] npm, eslint, prettier, scripts, and other dev environment settings set up correctly
- [x] properly formatted source code, with extraneous comments removed (e.g., `// TODO`)
- [x] structured logging with Pino, uses proper log levels throughout code (i.e., make sure you have used info, debug, warn, error logs everywhere). No `console.log()`.
- [x] API with express, middleware, routes, error handling set up correctly
- [x] environment variables properly managed via `dotenv`, `.env` files
- [x] no secrets or generated files included in git repos (i.e., only source code and config files)
- [x] unit testing using `jest` and `supertest` set up correctly
- [x] proper testing vs. development environment setup (configs, env, scripts)
- [x] test coverage reporting/scripts configured properly
- [x] GitHub Actions CI Workflow for eslint and unit tests set up correctly
- [x] all API routes use proper `/v1` version
- [x] all routes are secured using Passport.js based auth, configurable using either Cognito or Basic Auth
- [x] fragment data model working with In-Memory DB, with unit tests
- [x] success and error responses use correct JSON format, with unit tests. See 3.1, 3.2.
- [x] `GET /` returns a non-cacheable health check, with unit tests. See 4.1.
- [x] `POST /fragments` creates a fragment (only plain text support required at this point), with unit tests. See 4.3.
- [x] `GET /fragments` returns a list of the authenticated user's existing fragment IDs, if any. See 4.4.
- [x] `GET /fragments/:id` returns an existing fragment (only plain text support required at this point), with unit tests. See 4.5.
- [x] server deployed manually, and successfully running on AWS EC2 instance, configured via `.env` to use Amazon Cognito for user authorization
