### ISSUE TITLE
Assignment 2 - API server checklist

### ISSUE THREAD

**Issue by lctoye** [lctoye/fragments#2]
## API Server Checklist

- [x] Clean, properly formatted code with proper logging and comments
- [x] `Dockerfile` and `.dockerignore` added to `fragments` GitHub repo
- [x] `Dockerfile` employs [Docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) for creating Docker Images
- [x] `Dockerfile` uses a multi-stage Docker Build produces, producing the smallest possible production Docker Image of your `fragments` node server
- [x] `fragments` Docker image is hosted as a public repository at [Docker Hub](https://hub.docker.com/) under your account
- [x] [Docker Hub](https://hub.docker.com/) account secrets properly stored in GitHub repo
- [x] `fragments` Docker image automatically built and pushed to [Docker Hub](https://hub.docker.com/) on every new commit to the `main` branch via GitHub Actions CI workflow
- [x] `POST /fragments` can now create any `text/*` or `application/json` fragments (i.e., you don't need to support images until [Assignment 3](../assignment-03/README.md)), with unit tests. See 4.3.
- [x] `GET /fragments?expand=1` now returns expanded fragment metadata for an authenticated user. See 4.4.1.
- [x] `GET /fragments/:id` returns an existing fragment's data with the expected `Content-Type`, with unit tests. See 4.5.
- [x] `GET /fragments/:id/info` returns an existing fragment's metadata, with unit tests. See 4.7.
- [x] `GET /fragments/:id.ext` returns an existing fragment's data converted to a supported type. Initially, you only need to support Markdown fragments (`.md`) converted to HTML (`.html`) using [markdown-it](https://github.com/markdown-it/markdown-it) (i.e., you don't have to do other conversions until [Assignment 3](../assignment-03/README.md))
- [x] Unit test coverage should be at 80% or above, targeting all expected source files
- [x] `fragments` Docker container is running manually on EC2 using pre-built [Docker Hub](https://hub.docker.com/) image (i.e., without building manually on EC2)
