### ISSUE TITLE
API Server Checklist

### ISSUE THREAD

**Issue by lctoye** [lctoye/fragments#3]
## API Server Checklist

- [x] Clean code
- [x] Docker Compose setup to run `fragments`, DynamoDB Local, and S3 LocalStack containers together in development and GitHub Actions CI workflow for integration testing
- [x] Integration tests using [Hurl](https://hurl.dev/) and `docker compose` properly set-up with scripts to easily run them
- [x] Integration test cases cover all major aspects of the Fragments HTTP API Specification (i.e., all routes, success and error cases) using HTTP Basic Auth (i.e., testing with Amazon Cognito not necessary)
- [x] Unit tests and Integration tests run on every commit to `main` branch via GitHub Actions CI workflow
- [x] Fragments Metadata stored in Amazon DynamoDB, with integration tests using DynamoDB Local container
- [x] Fragments Data stored in Amazon S3, with integration tests using LocalStack container
- [x] `fragments` server data model configurable via `.env` to run using either `MemoryDB` or AWS (S3, DynamoDB)
- [x] `POST /fragments` can create any supported text, image or JSON fragments, with tests. See 4.3.
- [x] `PUT /fragments:id` can update an authenticated user's existing fragment, with tests. See 4.6.
- [x] `DELETE /fragments/:id` can delete an authenticated user's existing fragment, with tests. See 4.8.
- [x] `GET /fragments/:id.ext` allows conversion of all fragment types to other supported types. Image conversions use [sharp](https://sharp.pixelplumbing.com/) module
- [x] Conversion between all supported fragment types and conversions via `.ext`, with tests
- [x] AWS account and ECR repository secrets properly stored in GitHub repo
- [x] `fragments` Docker image automatically built and pushed to Amazon Elastic Container Registry (ECR) on every new git Tag via GitHub Actions CD workflow
- [x] `fragments` Docker container automatically deployed to Elastic Container Service using pre-built Amazon ECR Docker image on every git tag via GitHub Actions CD workflow
